version: '3'

services:
  kafka:
    container_name: kafka_for_spring
    image: apache/kafka:3.7.0
    volumes:
      - kafka-data:/var/lib/kafka/data  # Optional: Persist Kafka data
    ports:
      - "9092:9092"

  postgres:
    container_name: postgresql_for_spring
    image: postgres:16.1
    environment:
      POSTGRES_USER: person
      POSTGRES_PASSWORD: person1234
      POSTGRES_DB: kafkadata
    volumes:
      - postgres-data:/var/lib/postgresql/data  #Optional: Persist PostgreSQL data
    ports:
      - "5432:5432"

volumes:
  # Optional volume for persistent Kafka data
  kafka-data: { }
  # Optional volume for persistent Postgres data
  postgres-data: { }